### ISSUE TITLE
T2_US_UMD FE cannot connect due to DB access error

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/ops#20]
httpd is up running. Port 8443 was active but http request timed out. Logging error below. @juztas 

```
[Fri May 27 13:58:37.756766 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804] mod_wsgi (pid=22432): Exception occurred processing WSGI script '/var/www/wsgi-scripts/sitefe.wsgi'.
[Fri May 27 13:58:37.757004 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804] Traceback (most recent call last):
[Fri May 27 13:58:37.757064 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]   File "/var/www/wsgi-scripts/sitefe.wsgi", line 2, in <module>
[Fri May 27 13:58:37.757070 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]     from SiteFE.REST.app import application
[Fri May 27 13:58:37.757077 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]   File "/usr/local/lib/python3.6/site-packages/DTNRMSiteFE-210312-py3.6.egg/SiteFE/REST/app.py", line 269, in <module>
[Fri May 27 13:58:37.757080 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]     method = importlib.import_module(name)
[Fri May 27 13:58:37.757086 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
[Fri May 27 13:58:37.757089 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri May 27 13:58:37.757095 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]   File "/usr/local/lib/python3.6/site-packages/DTNRMSiteFE-210312-py3.6.egg/SiteFE/REST/AppCalls/DeltaApp.py", line 29, in <module>
[Fri May 27 13:58:37.757099 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]     DELTABACKEND = frontendDeltaModels(config=CONFIG)
[Fri May 27 13:58:37.757104 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]   File "/usr/local/lib/python3.6/site-packages/DTNRMSiteFE-210312-py3.6.egg/SiteFE/REST/Models/DeltaModels.py", line 45, in __init__
[Fri May 27 13:58:37.757107 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]     policer = polS.PolicyService(config, sitename)
[Fri May 27 13:58:37.757114 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]   File "/usr/local/lib/python3.6/site-packages/DTNRMSiteFE-210312-py3.6.egg/SiteFE/PolicyService/policyService.py", line 55, in __init__
[Fri May 27 13:58:37.757117 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]     self.hosts = getAllHosts(self.sitename, self.logger)
[Fri May 27 13:58:37.757123 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]   File "/usr/local/lib/python3.6/site-packages/DTNRMSiteFE-210312-py3.6.egg/DTNRMLibs/FECalls.py", line 27, in getAllHosts
[Fri May 27 13:58:37.757126 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]     for site in dbObj.get('hosts'):
[Fri May 27 13:58:37.757132 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]   File "/usr/local/lib/python3.6/site-packages/DTNRMSiteFE-210312-py3.6.egg/DTNRMLibs/DBBackend.py", line 205, in get
[Fri May 27 13:58:37.757135 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]     callExit, colname, dbout = self._caller(self.getcall('get', calltype), limit, orderby, search)
[Fri May 27 13:58:37.757155 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]   File "/usr/local/lib/python3.6/site-packages/DTNRMSiteFE-210312-py3.6.egg/DTNRMLibs/DBBackend.py", line 200, in _caller
[Fri May 27 13:58:37.757159 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]     return self.db.execute_get(fullquery)
[Fri May 27 13:58:37.757164 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]   File "/usr/local/lib/python3.6/site-packages/DTNRMSiteFE-210312-py3.6.egg/DTNRMLibs/DBBackend.py", line 97, in execute_get
[Fri May 27 13:58:37.757167 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]     raise ex
[Fri May 27 13:58:37.757172 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]   File "/usr/local/lib/python3.6/site-packages/DTNRMSiteFE-210312-py3.6.egg/DTNRMLibs/DBBackend.py", line 92, in execute_get
[Fri May 27 13:58:37.757175 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]     self.initialize()
[Fri May 27 13:58:37.757180 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]   File "/usr/local/lib/python3.6/site-packages/DTNRMSiteFE-210312-py3.6.egg/DTNRMLibs/DBBackend.py", line 83, in initialize
[Fri May 27 13:58:37.757183 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804]     database=self.mdb)
[Fri May 27 13:58:37.757201 2022] [wsgi:error] [pid 22432:tid 140209292084992] [client 206.196.180.134:17804] mariadb.OperationalError: Access denied for user 'root'@'localhost' (using password: NO)

```

**Comment by xi-yang** [comment]
FYI, the Hawaii FE went irresponsive after running for a while. I saw the following in logging.

```
[Thu Jun 02 13:34:33.751061 2022] [wsgi:error] [pid 11442:tid 140512933701376] [client 128.171.123.10:7369] mariadb.OperationalError: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
```

So looks like DB issue is the most common one causing FE down.

**Comment by xi-yang** [comment]
In another case, FE stopped responding as the FE MAIN config file under /tmp gets corrupted somehow (after it had already been working)
<img width="1073" alt="Screen Shot 2022-06-14 at 10 49 46 AM" src="https://user-images.githubusercontent.com/6596456/173608132-c96fa19e-4dfe-4fb3-94a6-84178eda50ef.png">
<img width="376" alt="Screen Shot 2022-06-14 at 10 48 18 AM" src="https://user-images.githubusercontent.com/6596456/173608145-1bc7606f-3c0c-49d9-a7ef-bdba96103a76.png">

**Comment by xi-yang** [comment]
In a third scenario (one day after fixing the above), all python daemons crashed with httpd still running but no more httpd logging. This was not due to disk full.
